Repo:
  - .github/*
Backend:
  - Controllers/*
  - DbContexts/*
  - Dtos/*
  - Entities/*
  - Helpers/*
  - Migrations/*
  - Profiles/*
  - Repositories/*
  - ResourceParameters/*
  - Services/*
Frontend:
  - ClientApp/*
Others:
  - Dockerfile*