# Staging
FROM mcr.microsoft.com/dotnet/core/sdk:3.1 as stage
WORKDIR /Stage
COPY . .
RUN dotnet restore
ARG runnpm
# Install node so can call dotnet publish to publish the backend (Will remove later)
RUN apt-get update -yq \
    && apt-get install curl gnupg -yq \
    && curl -sL https://deb.nodesource.com/setup_13.x | bash \
    && apt-get install nodejs -yq
RUN dotnet publish -c Release -o output
RUN ls output
WORKDIR /Stage/output
RUN ls -l

# Runtime
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 as runtime
WORKDIR /Code
# Copy Certs
RUN mkdir Certs
RUN ls -l
# COPY ./Certs ./Certs
# RUN ls Certs
COPY --from=stage /Stage/output .
# Env
# ENV ASPNETCORE_URLS=https://*:$PORT;http://*:$PORT
# ENV ASPNETCORE_ENVIRONMENT=Production
# Copy script from local
COPY ./wait-for-it.sh .
CMD dos2unix wait-for-it.sh
RUN chmod +x wait-for-it.sh
# Transfer to wwwroot folder
RUN mv ClientApp/build wwwroot
RUN ls -l
# RUN ls ClientApp/build
RUN ls wwwroot
EXPOSE 80
CMD [ "./wait-for-it.sh", "sql:1433", "-t", "0", "--", "dotnet",  "DotNetCoreReactREST.dll" ]