version: '3.7'
services: 
    backend:
        build:
            context: .
            dockerfile: Dockerfile-backend
        volumes:
            - ./Logs:/Code/Logs
        ports:
            - "5001:80"
        restart: always
    #frontend:
    #    build:
    #        context: .
    #        dockerfile: Dockerfile-frontend
    #    depends_on:
    #        - backend
    #    ports:
    #        - 8080:80
    #    restart: always
    sql:
        image: mcr.microsoft.com/mssql/server
        environment: 
            - ACCEPT_EULA=Y
            - SA_PASSWORD=P@ssw0rd
        depends_on: 
            - backend
        #    - frontend
        volumes: 
            - ./data:/var/opt/mssql/data
        ports: 
            - 1433:1433
        restart: always