version: '3.7'
services: 
    backend:
        build:
            context: .
            dockerfile: Dockerfile-backend
        ports:
            - 5001:80
        restart: always
        volumes:
            - frontend:/Code/ClientApp/build
    frontend:
        build:
            context: .
            dockerfile: Dockerfile-frontend
        depends_on:
            - backend
        ports:
            - 8080:80
        volumes:
            - frontend:/usr/share/nginx/html:ro
        restart: always
    sql:
        image: mcr.microsoft.com/mssql/server
        environment: 
            - ACCEPT_EULA=Y
            - SA_PASSWORD=P@ssw0rd
        depends_on: 
            - backend
            - frontend
        #volumes: 
        #    - backend:/var/opt/mssql/data
        ports: 
            - 1433:1433
        restart: always
volumes:
    frontend:
    backend: