version: '3.7'
services: 
    backend:
        build:
            context: .
            dockerfile: Dockerfile-backend
            args:
                runnpm: "false"
        volumes:
            - ./Logs:/Code/Logs
            - ./Certs:/Code/Certs
        ports:
            - "5001:80"
        environment:
            - ASPNETCORE_URLS=https://+;http://+
            - ASPNETCORE_HTTPS_PORT=5001
            - APNETCORE_Kestrel__Certificates__Default__Path=/Code/Certs/dotnetcorereactrest.pfx
            - ASPNETCORE_Kestrel__Certificates__Default__Password=dotnetcorereactrest
        restart: always
    #frontend:
    #    build:
    #        context: .
    #        dockerfile: Dockerfile-frontend
    #    depends_on:
    #        - backend
    #    ports:
    #        - 8080:80
    #    restart: always
    sql:
        image: mcr.microsoft.com/mssql/server
        environment: 
            - ACCEPT_EULA=Y
            - SA_PASSWORD=P@ssw0rd
        depends_on: 
            - backend
        #    - frontend
        volumes: 
            - ./data:/var/opt/mssql/data
        ports: 
            - 1433:1433
        restart: always